//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pylorak.TinyWall.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKSoft.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File and Printer Sharing.
        /// </summary>
        internal static string File_and_Printer_Sharing {
            get {
                return ResourceManager.GetString("File_and_Printer_Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered ICMP Traffic.
        /// </summary>
        internal static string Filtered_ICMP_Traffic {
            get {
                return ResourceManager.GetString("Filtered_ICMP_Traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pingable local machine.
        /// </summary>
        internal static string Pingable_local_machine {
            get {
                return ResourceManager.GetString("Pingable_local_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinyWall.
        /// </summary>
        internal static string TinyWall {
            get {
                return ResourceManager.GetString("TinyWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN L2TP/IPSec.
        /// </summary>
        internal static string VPN_L2TP_IPSec {
            get {
                return ResourceManager.GetString("VPN_L2TP_IPSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN PPTP.
        /// </summary>
        internal static string VPN_PPTP {
            get {
                return ResourceManager.GetString("VPN_PPTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Defender.
        /// </summary>
        internal static string Windows_Defender {
            get {
                return ResourceManager.GetString("Windows_Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows DHCP Client.
        /// </summary>
        internal static string Windows_DHCP_Client {
            get {
                return ResourceManager.GetString("Windows_DHCP_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows DNS Client.
        /// </summary>
        internal static string Windows_DNS_Client {
            get {
                return ResourceManager.GetString("Windows_DNS_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Network Discovery.
        /// </summary>
        internal static string Windows_Network_Discovery {
            get {
                return ResourceManager.GetString("Windows_Network_Discovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Remote Assistance.
        /// </summary>
        internal static string Windows_Remote_Assistance {
            get {
                return ResourceManager.GetString("Windows_Remote_Assistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Remote Desktop.
        /// </summary>
        internal static string Windows_Remote_Desktop {
            get {
                return ResourceManager.GetString("Windows_Remote_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Store Update.
        /// </summary>
        internal static string Windows_Store_Update {
            get {
                return ResourceManager.GetString("Windows_Store_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Time Sync.
        /// </summary>
        internal static string Windows_Time_Sync {
            get {
                return ResourceManager.GetString("Windows_Time_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Update.
        /// </summary>
        internal static string Windows_Update {
            get {
                return ResourceManager.GetString("Windows_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSL 2.
        /// </summary>
        internal static string WSL_2 {
            get {
                return ResourceManager.GetString("WSL_2", resourceCulture);
            }
        }
    }
}
