//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pylorak.TinyWall.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pylorak.TinyWall.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All applications.
        /// </summary>
        internal static string AllApplications {
            get {
                return ResourceManager.GetString("AllApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFilesFileFilter {
            get {
                return ResourceManager.GetString("AllFilesFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all firewall exceptions?.
        /// </summary>
        internal static string AreYouSureYouWantToRemoveAllExceptions {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveAllExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get executable path. Whitelisting failed..
        /// </summary>
        internal static string CannotGetExecutablePathWhitelisting {
            get {
                return ResourceManager.GetString("CannotGetExecutablePathWhitelisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get path of process..
        /// </summary>
        internal static string CannotGetPathOfProcess {
            get {
                return ResourceManager.GetString("CannotGetPathOfProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the inner area of any open window to select its application for whitelisting..
        /// </summary>
        internal static string ClickOnAWindowWhitelisting {
            get {
                return ResourceManager.GetString("ClickOnAWindowWhitelisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with the TinyWall service encountered an error..
        /// </summary>
        internal static string CommunicationWithTheServiceError {
            get {
                return ResourceManager.GetString("CommunicationWithTheServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, possibly compromised.
        /// </summary>
        internal static string CompromisedApplication {
            get {
                return ResourceManager.GetString("CompromisedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file has been successfully exported..
        /// </summary>
        internal static string ConfigurationHasBeenExported {
            get {
                return ResourceManager.GetString("ConfigurationHasBeenExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file has been successfully imported. Press Apply in the Manage window to make the new settings permanent..
        /// </summary>
        internal static string ConfigurationHasBeenImported {
            get {
                return ResourceManager.GetString("ConfigurationHasBeenImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import configuration file..
        /// </summary>
        internal static string ConfigurationImportError {
            get {
                return ResourceManager.GetString("ConfigurationImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not apply firewall settings due to an internal error..
        /// </summary>
        internal static string CouldNotApplySettingsInternalError {
            get {
                return ResourceManager.GetString("CouldNotApplySettingsInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not close process {0}({1})..
        /// </summary>
        internal static string CouldNotCloseProcess {
            get {
                return ResourceManager.GetString("CouldNotCloseProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not elevate privileges..
        /// </summary>
        internal static string CouldNotElevatePrivileges {
            get {
                return ResourceManager.GetString("CouldNotElevatePrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not elevate privileges necessary for update..
        /// </summary>
        internal static string CouldNotElevatePrivilegesForUpdate {
            get {
                return ResourceManager.GetString("CouldNotElevatePrivilegesForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not whitelist process of {0}..
        /// </summary>
        internal static string CouldNotWhitelistProcess {
            get {
                return ResourceManager.GetString("CouldNotWhitelistProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is missing or corrupt..
        /// </summary>
        internal static string DatabaseIsMissingOrCorrupt {
            get {
                return ResourceManager.GetString("DatabaseIsMissingOrCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you initiate the uninstall/update of TinyWall?.
        /// </summary>
        internal static string DidYouInitiateTheUninstall {
            get {
                return ResourceManager.GetString("DidYouInitiateTheUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        internal static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download interrupted..
        /// </summary>
        internal static string DownloadInterrupted {
            get {
                return ResourceManager.GetString("DownloadInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the update server.
        ///The server might be down, or please make sure that TinyWall has been granted internet access, then try again..
        /// </summary>
        internal static string ErrorCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow outgoing.
        /// </summary>
        internal static string FirewallModeAllowOut {
            get {
                return ResourceManager.GetString("FirewallModeAllowOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block all.
        /// </summary>
        internal static string FirewallModeBlockAll {
            get {
                return ResourceManager.GetString("FirewallModeBlockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string FirewallModeDisabled {
            get {
                return ResourceManager.GetString("FirewallModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autolearn.
        /// </summary>
        internal static string FirewallModeLearn {
            get {
                return ResourceManager.GetString("FirewallModeLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string FirewallModeNormal {
            get {
                return ResourceManager.GetString("FirewallModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string FirewallModeUnknown {
            get {
                return ResourceManager.GetString("FirewallModeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall rules for recognised {0} have been changed. Click this popup to edit the exception..
        /// </summary>
        internal static string FirewallRulesForRecognizedChanged {
            get {
                return ResourceManager.GetString("FirewallRulesForRecognizedChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall rules for unrecognised {0} have been changed. Click this popup to edit the exception..
        /// </summary>
        internal static string FirewallRulesForUnrecognizedChanged {
            get {
                return ResourceManager.GetString("FirewallRulesForUnrecognizedChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the newest version of TinyWall. No update necessary..
        /// </summary>
        internal static string NoUpdateAvailable {
            get {
                return ResourceManager.GetString("NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password fields do not match. Please verify your input..
        /// </summary>
        internal static string PasswordFieldsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordFieldsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        internal static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while TinyWall checks for available updates..
        /// </summary>
        internal static string PleaseWaitWhileTinyWallChecksForUpdates {
            get {
                return ResourceManager.GetString("PleaseWaitWhileTinyWallChecksForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the port list is invalid.
        ///You can use one or more numbers in the range of 1-65535, separated by commas. An asterix (*) can also be used to refer to all possible ports..
        /// </summary>
        internal static string PortListInvalid {
            get {
                return ResourceManager.GetString("PortListInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognised {0}.
        /// </summary>
        internal static string RecognizedApplication {
            get {
                return ResourceManager.GetString("RecognizedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching: {0}.
        /// </summary>
        internal static string SearchingPath {
            get {
                return ResourceManager.GetString("SearchingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results:.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has changed while you modified the preferences. To prevent losing settings, please make your changes again..
        /// </summary>
        internal static string SettingHaveChangedRetry {
            get {
                return ResourceManager.GetString("SettingHaveChangedRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting update....
        /// </summary>
        internal static string StartingUpdate {
            get {
                return ResourceManager.GetString("StartingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        internal static string SubjectTypeExecutable {
            get {
                return ResourceManager.GetString("SubjectTypeExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubjectTypeGlobal {
            get {
                return ResourceManager.GetString("SubjectTypeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string SubjectTypeService {
            get {
                return ResourceManager.GetString("SubjectTypeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP Package.
        /// </summary>
        internal static string SubjectTypeUwpApp {
            get {
                return ResourceManager.GetString("SubjectTypeUwpApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firewall is now allowing outgoing connections but blocks incoming..
        /// </summary>
        internal static string TheFirewallIsNowAllowsOutgoingConnections {
            get {
                return ResourceManager.GetString("TheFirewallIsNowAllowsOutgoingConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firewall is now blocking all inbound and outbound traffic..
        /// </summary>
        internal static string TheFirewallIsNowBlockingAllInAndOut {
            get {
                return ResourceManager.GetString("TheFirewallIsNowBlockingAllInAndOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firewall is now disabled..
        /// </summary>
        internal static string TheFirewallIsNowDisabled {
            get {
                return ResourceManager.GetString("TheFirewallIsNowDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firewall is now learning while letting all traffic through..
        /// </summary>
        internal static string TheFirewallIsNowLearning {
            get {
                return ResourceManager.GetString("TheFirewallIsNowLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firewall is now operating in the recommended mode..
        /// </summary>
        internal static string TheFirewallIsNowOperatingAsRecommended {
            get {
                return ResourceManager.GetString("TheFirewallIsNowOperatingAsRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firewall settings have been successfully updated..
        /// </summary>
        internal static string TheFirewallSettingsHaveBeenUpdated {
            get {
                return ResourceManager.GetString("TheFirewallSettingsHaveBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TinyWall service is unavailable. Please make sure it is installed and started, then retry..
        /// </summary>
        internal static string TheTinyWallServiceIsUnavailable {
            get {
                return ResourceManager.GetString("TheTinyWallServiceIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinyWall.
        /// </summary>
        internal static string TinyWall {
            get {
                return ResourceManager.GetString("TinyWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinyWall has been unlocked. You may now issue commands that modify the configuration..
        /// </summary>
        internal static string TinyWallHasBeenUnlocked {
            get {
                return ResourceManager.GetString("TinyWallHasBeenUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinyWall is current locked. Unlock and retry..
        /// </summary>
        internal static string TinyWallIsCurrentlyLocked {
            get {
                return ResourceManager.GetString("TinyWallIsCurrentlyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinyWall Settings.
        /// </summary>
        internal static string TinyWallSettingsFileFilter {
            get {
                return ResourceManager.GetString("TinyWallSettingsFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinyWall Updater.
        /// </summary>
        internal static string TinyWallUpdater {
            get {
                return ResourceManager.GetString("TinyWallUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string TrafficIn {
            get {
                return ResourceManager.GetString("TrafficIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string TrafficOut {
            get {
                return ResourceManager.GetString("TrafficOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related files found
        ///The selected executable could be part of {0}. To ensure that this application can be used without limitations, it is recommended to also unblock some other files..
        /// </summary>
        internal static string UnblockApp {
            get {
                return ResourceManager.GetString("UnblockApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel whitelisting.
        /// </summary>
        internal static string UnblockAppCancel {
            get {
                return ResourceManager.GetString("UnblockAppCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide related executables.
        /// </summary>
        internal static string UnblockAppShowRelated {
            get {
                return ResourceManager.GetString("UnblockAppShowRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock all recommended files.
        /// </summary>
        internal static string UnblockAppUnblockAllRecommended {
            get {
                return ResourceManager.GetString("UnblockAppUnblockAllRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock only selected file.
        /// </summary>
        internal static string UnblockAppUnblockOnlySelected {
            get {
                return ResourceManager.GetString("UnblockAppUnblockOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown application.
        /// </summary>
        internal static string UnknownApplication {
            get {
                return ResourceManager.GetString("UnknownApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock failed. Try again with another passphrase..
        /// </summary>
        internal static string UnlockFailed {
            get {
                return ResourceManager.GetString("UnlockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until reboot.
        /// </summary>
        internal static string UntilReboot {
            get {
                return ResourceManager.GetString("UntilReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version {0} of TinyWall is available. Do you want to update now?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version {0} of TinyWall is available. Click this bubble to start the update process..
        /// </summary>
        internal static string UpdateAvailableBubble {
            get {
                return ResourceManager.GetString("UpdateAvailableBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitelisting cancelled..
        /// </summary>
        internal static string WhitelistingCancelled {
            get {
                return ResourceManager.GetString("WhitelistingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        internal static string XHour {
            get {
                return ResourceManager.GetString("XHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        internal static string XHours {
            get {
                return ResourceManager.GetString("XHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string XMinutes {
            get {
                return ResourceManager.GetString("XMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start automatic learning?
        ///In its automatic learning mode TinyWall will allow all traffic and remember which applications have used the network. When you exit learning mode, TinyWall will add exceptions for you automatically. Note however, that rules cannot be learned for &quot;Special Exceptions&quot; of the configuration.
        ///
        ///Before entering learning mode, make sure that your system is free of any malware. It is best to run learning mode on freshly installed systems and it is recommended tha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YouAreAboutToEnterLearningMode {
            get {
                return ResourceManager.GetString("YouAreAboutToEnterLearningMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have administrative privileges needed to perform this operation.
        ///Select Elevate from the tray menu and try again..
        /// </summary>
        internal static string YouDoNotHaveAdministrativePrivilegesNeeded {
            get {
                return ResourceManager.GetString("YouDoNotHaveAdministrativePrivilegesNeeded", resourceCulture);
            }
        }
    }
}
